dist: xenial
sudo: required
language: python
python:
- 3.7
env:
  global:
  - TOXENV="py37"
  - DEPLOY=yes
  - LANG=en_US.UTF-8
install:
- make install
- pip install coveralls
script:
- make lint
- make test
after_success:
- coveralls
deploy:
  provider: pypi
  user: akariv
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$DEPLOY = yes"
  password:
    secure: icooh1z6MH4lzwNeWVoxJOH0btfEHbwLgN2MpJcaMBMgd09qWF182UZrMAZwsc1JCV8LvWj6GdvaHhtiefSVng1qKVX7DLfkbZi1YFzJfsvqxyA0OFIvDrcVvux1Ht+/wc9ZLOg8y1SUB1O8kD73AQncnHHotRxIxJEWkOxBeOQVAjZVpE5F6CtH7jUO60i4dAz1cwZfAUPbtTD8tEK4ukAPi4465K6Ptc5YKNiUUO69978CAVvulHhTZ7cfi/lv91ndB6D2LR6fiyfvfkdgKiFLGMesDALiMJo6tVHRLyab4wENP9gWWo50rVHesddjXmNPyiilKSIciO3uD5ULiWsT9uuNP/CqfZWaYqN/1zD9EQ3I7hfHTSdAcCdg1x6WtDVSp4WbJ8d1sj+cZxHmEyU1QwMqoExWO5zrEwG6CJWw3YrLNrgkt3th+UU0hJE0ZXgIEoBaGj7reoOhOKYg7FjSJ6Vn7nZ5VL5+a7heLxBjKnYMS0b4VP/+D7eSFPRCCt3N9Z3RvPRs2RyvvfR1wrkqNI+fsv2IAmV18XrXkldPvZMsiSYk9J2usKAwe5OlBB6EQpOSp2WP8HYHbwM213nA1YQoNX2iAlvMhulZxv2GoRms0/0qrMiK+mYvaYgiCuid02SfB0WCMkRDC7/ad9J3W72iWjwAzvgMASQcmUc=
